#!/usr/bin/env sh

printf "\n=== Diffs inside of /etc/portage ===\n\n"
diff /etc/portage gentoo_install/etc/portage --recursive --color=always
printf "\n=== Diffs outside of /etc/portage: ===\n\n"
find gentoo_install -path 'gentoo_install/etc/portage' -prune -o -type f -print |
  sed 's/^gentoo_install//' |
  while read -r file; do
    if [ -f "${file}" ]; then
      diff_script_difference="$(diff "${file}" "gentoo_install${file}" --color=always)"
      if [ -n "$diff_script_difference" ]; then
        echo "Comparing ${file} with gentoo_install${file}"
        printf "%s\n" "$diff_script_difference"
      fi
    else
      echo "${file} does not exist."
    fi
  done
